### ISSUE TITLE
Support tokenless upload

### ISSUE THREAD

**Issue by s0undt3ch** [codecov/codecov-cli#259] opened 2023-09-16 17:30 UTC
Workflows which rely on pull request from forks can't access the repository secrets, so this new CLI is completely useless on that scenario.

**Comment by rohan-at-sentry** [comment] 2023-10-25 15:29
@s0undt3ch this is something we're [actively working on.](https://github.com/codecov/engineering-team/issues/665)

I'd like to close this issue as there is another issue that is raised , which is a dupe of this.

https://github.com/codecov/feedback/issues/112 

If you'd like to follow along with that one, I'll post an update when we have this fixed.

**Closed by rohan-at-sentry** 2023-10-25 15:29 UTC
Labels: bug
